name: slash-phase3
language: python
python:
  - "3.6"
before_install:
  - python -m pip install --upgrade pip
install:
  - pip install -r requirements.txt
  - pip install codecov
before_script:
  - sudo apt-get update
sudo: required
script:
  - cd tests 
  - pytest 
